### ISSUE TITLE
All seems ok but no values are shown...

### ISSUE THREAD

**Issue by luisgodelmo** [stelford/home-assistant_inkbird#3]
Hi, I'm new and lost... I've been for two months trying to display 3 IBS-TH1plus in hassio without success... Your screenshots are my only hope! 
What I did: copied your 6 files + helper scripts folder in a folder called inkbird inside config/custom_components. Then added 3 devices following the indicated structure in configuration.yaml. Saved and restarted hass. No errors or warnings are shown, and the humidity, tenperature and battery indicators are shown for the 3 sensors... But they appear as "unknown"... No value is ever shown. 
MACs are correct as I made many proximity tests with my phone, and they are sticked to the raspberry. 
Could I be missing some previous steps related to bluetooth/BLE configuration, addon installation, coupling, a dongle, etc? 
Or maybe this is not for hass.io in hassOS3.5 in a raspberry pi4?
I've seen your last post about going through esp32 and mqtt, would you recommend to directly go for this option?
Any help will be very very appreciated! Thank you!

**Comment by bigandsmalltortoise** [comment]
I am having the exact same problem, also using Raspberry pi4.  Sensor values are displayed as "unknown" :(  I can't figure it out!

**Comment by mindcanal** [comment]
Same here, also on a pi4

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 465, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/inkbird/sensor.py", line 139, in update
    self.handleDiscovery(dev)
  File "/config/custom_components/inkbird/sensor.py", line 167, in handleDiscovery
    battery = int(value[14:16], 16)
ValueError: invalid literal for int() with base 16: ''`
