### ISSUE TITLE
Bluetooth error

### ISSUE THREAD

**Issue by brianx87** [stelford/home-assistant_inkbird#6]
Something has happened causing a bluetooth error and restoring HA from a snapshot didn't fix this issue.

```
2020-10-18 21:32:06 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for inkbird which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-18 21:32:40 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up inkbird platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/inkbird/sensor.py", line 76, in setup_platform
    inkbird_devices.append( InkbirdUpdater(hass, inkbird_devices) )
  File "/config/custom_components/inkbird/sensor.py", line 93, in __init__
    self.scanner.start()
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 790, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'le on' (code: 17, error: Invalid Index)
```

**Comment by brianx87** [comment]
Issue is with ha os 14.4, resolved by downgrading to 14.3
